from django.urls import path
from .views import (
    WarriorListAPIView, 
    WarriorCreateAPIView,
    WarriorRetrieveAPIView,
    WarriorUpdateAPIView,
    WarriorDestroyAPIView,
    ProfessionListAPIView, 
    ProfessionCreateAPIView,
    ProfessionRetrieveAPIView,
    ProfessionUpdateAPIView,
    ProfessionDestroyAPIView,
    SkillListAPIView, 
    SkillCreateAPIView,
    SkillRetrieveAPIView,
    SkillUpdateAPIView,
    SkillDestroyAPIView,
)

urlpatterns = [
    path('warriors/', WarriorListAPIView.as_view()),
    path('warriors/create/', WarriorCreateAPIView.as_view()),
    path('warriors/<int:pk>/', WarriorRetrieveAPIView.as_view()),
    path('warriors/<int:pk>/update/', WarriorUpdateAPIView.as_view()),
    path('warriors/<int:pk>/delete/', WarriorDestroyAPIView.as_view()),
    path('profession/', ProfessionListAPIView.as_view()),
    path('profession/create/', ProfessionCreateAPIView.as_view()),
    path('profession/<int:pk>/', ProfessionRetrieveAPIView.as_view()),
    path('profession/<int:pk>/update/', ProfessionUpdateAPIView.as_view()),
    path('profession/<int:pk>/delete/', ProfessionDestroyAPIView.as_view()),
    path('skills/', SkillListAPIView.as_view()),
    path('skills/create/', SkillCreateAPIView.as_view()),
    path('skills/<int:pk>/', SkillRetrieveAPIView.as_view()),
    path('skills/<int:pk>/update/', SkillUpdateAPIView.as_view()),
    path('skills/<int:pk>/delete/', SkillDestroyAPIView.as_view()),
]
